### ISSUE TITLE
message type error

### ISSUE THREAD

**Issue by guihomework** [ubi-agni/pyhsm#11]
a pyhsm code is connected to the hsm viewer and produces some msg filling errors see lower.

```
rostopic info /hsm_introspection/structure
Type: pyhsm_msgs/HsmStructure
Publishers: 
 * /pick_place_py (http://brutus:45761/)
Subscribers: 
 * /hsm_viewer (http://brutus:45979/)`
```
nothing published yet
```
rostopic echo /hsm_introspection/structure
WARNING: no messages received and simulated time is active
```

in the ```pick_place_py``` terminal which wants to send something out, there is this message, probably the introspection sending wrong stuff and hence the message does not even reach the rostopic echo.
```
[WARN] [1583167410.325663, 197.358000]: Inbound TCP/IP connection failed: field states[].transitions[].events[] must be of type str
```

**Comment by rhaschke** [comment]
Fixed. Problem was the special event `any_event`, which wasn't stringified before sending.
