### ISSUE TITLE
pyhsm viewer freezes or crashes on structure update

### ISSUE THREAD

**Issue by guihomework** [ubi-agni/pyhsm#13]
I started a state machine twice, with a tiny name modification inbetween the two runs, because I had done a typo error.

this lead the pyhsm viewer to freeze.

However, when redoing the change to try repeat, I had different behaviors. Sometime the new state would appear out of the tree, sometimes it would freeze, sometimes crash.

I think it can depend on the order the structure is stored in the message, maybe the modified name comes in an "initial_state attribute" before the new state name is given in the rest of the structure. 

attached is a zip file of 4 messages, 2 with the initial structure, and 2 with 2 different name change on the state add_object

[pyhsm_structure.zip](https://github.com/ubi-agni/pyhsm/files/4282229/pyhsm_structure.zip)

[EDIT] also had this once during the tests, maybe only at sigterm
```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/vol/famula/nightly/ros/melodic/lib/pyhsm/viewer.py", line 933, in _update_graph
    container = self._containers[path]
KeyError: u'pick_place_hsm/add_object'
```

**Comment by rhaschke** [comment]
The viewer wasn't yet handling a restructuring of the HSM. I fixed several issues today, including this one.
